name: HandmadeGiftShoppe
favicon: null
layout_spectrum: 0.74292
typography_spectrum: 0.75293
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#313131'
    - '#16fefe'
    - '#fe9d06'
    - '#7c5b14'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
