name: HandmadeGiftShoppe
favicon: null
layout_spectrum: 0.00892680580727756
typography_spectrum: 0.33768806024454534
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.37434460455551744
  lightness: 0.4797222022898495
  saturation: 0.04748456203378737
  rhythmicContrast: 0.5547664093319327
purpose: []
